server:
  port: 8085
# Database configuration properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inofficemarketplace_db
    username: root
    password: ENC(XDm4WBD3KGCOZe4ZwVFcyw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
#  security:
#    user:
#      name: rahul
#      password: rahul
